/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "signals.h"
#include "uart.h"
#include <stdio.h>
#include "adc.h"
#include "fir_filter.h"




extern float32_t lfp_1hz_2hz_impulse_response [LPF_1HZ_2H_LEN];
uint32_t sensor_value;
uint32_t filtered_sensor_value;

fir_filter_type lpf_fir;





static void plot_input_signal(void);
static void pseudo_delay(void);


int main(void)
{
	//Enable Floating Point Unit
	SCB->CPACR |= ((3UL<<20)| (3UL<<22));	//full access to cp11 and cp10 (refer to cortex user guide (fpu))

	pa1_adc_init();
	start_conversion();
	uart2_tx_init();

	FIR_filter_init(lpf_fir, lfp_1hz_2hz_impulse_response, LPF_1HZ_2H_LEN);
	while(1){
		//printf("Hello from STM32\n\r");
		sensor_value=adc_read();
		filtered_sensor_value=FIR_filter_update(&lpf_fir, sensor_value);
		pseudo_delay();
	}
}
static void plot_input_signal(void){
	for(int i=0;i< KHZ1_15_SIG_LEN ;i++){
		pseudo_delay();
	}
}



static void pseudo_delay(void){
	 for(int i=0;i <100000; i++){

	 }
}




