/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "signals.h"
#include "uart.h"
#include <stdio.h>
#include "systick.h"



#define GPIOAEN			(1U<<0)
#define PIN5			(1U<<5)
#define LED_PIN			PIN5


extern float _5hz_signal[HZ_5_SIG_LEN];
extern float32_t inputSignal_f32_1kHz_15kHz[KHZ1_15_SIG_LEN];
extern float32_t  impulse_response[IMP_RESP_LEN];

float32_t ReX[KHZ1_15_SIG_LEN/2];
float32_t ImX[KHZ1_15_SIG_LEN/2];

float re,im;


static void plot_input_signal(void);
static void pseudo_delay(void);

static void DFT(float32_t * source, uint32_t length, float32_t * ReX, float32_t * ImX);



int main(void)
{
	//Enable Floating Point Unit
	SCB->CPACR |= ((3UL<<20)| (3UL<<22));	//full access to cp11 and cp10 (refer to cortex user guide (fpu))

	uart2_tx_init();
	systick_init();

	DFT(inputSignal_f32_1kHz_15kHz, (uint32_t) KHZ1_15_SIG_LEN, ReX, ImX);

	plot_input_signal();
	while(1){
		//printf("Hello from STM32\n\r");
	}
}
static void plot_input_signal(void){
	for(int i=0;i< KHZ1_15_SIG_LEN/2 ;i++){
		re=fabs(ReX[i]);
		printf("%f\n\r",re);
		im=fabs(ImX[i]);
		pseudo_delay();
	}
}

static void pseudo_delay(void){
	 for(int i=0;i <100000; i++){

	 }
}

static void DFT(float32_t * source, uint32_t length, float32_t * ReX, float32_t * ImX){
	for(int i=0;i<length/2;i++){
		ReX[i]=0;
		ImX[i]=0;
	}
	for(int i=0;i<length/2;i++){
		for(int j=0;j<length;j++){
			ReX[i]+= source[j]*cos(2*PI*j*i/length);
			ImX[i]+= source[j]*sin(2*PI*j*i/length);

		}
	}
}
